name: Latest blog post workflow

on:
  schedule:
    # 1시간마다 자동으로 실행
    - cron: '0 * * * *'
  workflow_dispatch: # 수동 실행 가능하도록 설정

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # 블로그 RSS 주소 (Jekyll 블로그는 보통 /feed.xml 임)
          feed_list: "https://mxxikr.github.io/feed.xml"
          # 보여줄 글 개수
          max_post_count: 5
          template: "$newline<a href='$url'>$title</a><br/><br/>"
